/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bbash;

/**
* Library class
*/
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
